export type AddNewInvestorType = {
    step: string,
    title:string,
    firstname:string,
    lastname:string,
    othername:string,
    email:string,
    phoneNumber:string,
    dob:string,
    ocupation:string,
    workplace:string,
    marital_status:string,
    gender:string,
    country:string,
    state:string,
    lga:string,
    city:string,
    address:string,

    next_firstname:string,
    next_middlename:string,
    next_lastname:string,
    next_gender:string,
    next_dob:string,
    next_country:string,
    next_state:string,
    next_lga:string,
    next_city: string,
    next_phonenumber:string,
    next_address:string,
    relationship:string,

    bank: string,
    account_number: string,
    account_name: string,
    officeId: string,
  }